### ISSUE TITLE
STEPS 3.6.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#187]
[](https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=472841561)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1140310103

**Comment by jagru20** [comment]
Dear @erikdsj,

we are in the process of adding metadata on your software to the [HBP Knowledge Graph](https://search.kg.ebrains.eu/?facet_type[0]=Software). We are about to add STEPS 3.5.0 to it and would like to ask you to check the collected metadata in the [spreadsheet ](https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1140310103) so that we can proceed. 

Thank you in advance 

Jan
HBP Software Curation Team

**Comment by jagru20** [comment]
developer left feedback. also, the current version is 3.6.0 we should integrate that one then.

**Comment by herr-zett** [comment]
Dear @erikdsj,

to finalize the integration of your software into the HBP Knowledge Graph, we need specific information about the funding of the software. For now, we only know that it is funded by the HBP. Could you please specify which grant agreement(s) apply to your software?

Daniel
HBP Software Curation Team

**Comment by erikdsj** [comment]
STEPS development is also funded by the Okinawa Institute of Science and Technology Graduate University.

Best regards,


Erik De Schutter

**Comment by jagru20** [comment]
Dear @erikdsj,

for curation quality purposes we want to include the Grant aggreement numbers for at least the HBP funding. Please provide this so we can continue integrating STEPS into EBRAINS. 

Thanks in advance

Jan Gründling
Software Curation

**Comment by jagru20** [comment]
released
