### ISSUE TITLE
Monsteer 0.7.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#189]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=2055069628

**Comment by s4safeld** [comment]
I finished integrating Monster as far as possible

**Comment by jagru20** [comment]
author's email in the spreadsheet does not work. Can you find a different one that ist more actual?

**Comment by PatriziaDuhr** [comment]
I found these two: eile@mailbox.org, eilemann@gmail.com

**Comment by jagru20** [comment]
Thanks!

**Comment by jagru20** [comment]
Dear Stefan @eile,
 
we are currently in the process to add metadata on software to the HBP Knowledge Graph. The major purpose is threefold: First, we would like to enable users to search for software additionally to data etc. through the knowledge graph search interface. Second, this enables to further map software to the curated data sets in the knowledge graph, and third, we plan to use this data as basis for provenance data entering the knowledge graph.
 
In this meta data curation process, we first research meta data of various types of software before we contact the responsible developer or contact person of that software in a second step.
 
Due to the latter, we contact you with the kind request to check the meta data we collected for your software **Monsteer 0.7.0** before we make it available in the HBP Knowledge Graph. Please use the link in the first comment of this issue to add suggestions to the meta data provided in the spreadsheet. If you have specific comments, please use the “Developer Comments” column (column D). In the same column, you may also find questions we had and we would like you to answer by commenting on it or adding additional information to the schema. We would also like to ask you to ignore all other software tools, which are not specifically mentioned above.
 
Please note that we assume all persons named in the metadata form have endorsed the processing and the publication of their names, E-Mail addresses and ORCID in the EBRAINS knowledge graph.
 
If you hover the various meta data categories, you get more information on what is actually meant with the various fields of the schema. Please note that these attributes, especially the feature-list, are not final. So if you have any suggestions or comments please let us know.  Therefore, if you have any questions or comments, do not hesitate to contact me or Jun.-Prof. Benjamin Weyers (@bweyers).
 
Please send us a short answer to this mail in the moment you finished your revision. Please try to send us feedback in two weeks from now. If you need more time, please let us know!
 
Thanks and kind regards,

Jan

**Comment by jagru20** [comment]
I think we can start integrating this, as the information seems to be sufficient, although the contact person did not respond to our request.
