### ISSUE TITLE
NetPyNe GUI 0.5.2

### ISSUE THREAD

**Issue by AnnHa2019** [bweyers/HBPVisCatalogue#26]
https://docs.google.com/spreadsheets/d/1d-e8VQagnfavD7JAxjtGlCRLXE5KUw689yn6Vkvf0Ek/edit#gid=2005137651

no copyright information available

**Comment by AnnHa2019** [comment]
Is NetPyNe UI a module?

**Comment by FeldNico** [comment]
> Is NetPyNe UI a module?

Yes

Because there is a already hosted version (http://www.netpyne.org/gui) there are no software requirement to use it. Therefore please add the website (http://www.netpyne.org/gui) as homepage. (We only want to list the minimal requirements and easiest way for the user to use the software. If the user wants to host it himself, he could go to the documentation)

**Comment by AnnHa2019** [comment]
Edited TODOs

**Comment by FeldNico** [comment]
Initial Email to Developer: 08.01.20

**Comment by FeldNico** [comment]
One small issue found: As we discussed yesterday, components are (mandatory or optional) parts of a software. Therefore NetPyNe is a Component of NetPyNe GUI and not the other way around. Please adjust.

**Comment by AnnHa2019** [comment]
Added NetPyNe as component

**Comment by FeldNico** [comment]
Reminder Email: 21.01.20
