### ISSUE TITLE
Synaptic events fitting (user's model) 1.3

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#266]
https://docs.google.com/spreadsheets/d/1ZNDNTfZwF7s6-x-ijlkIv4qdgV1MdRFEqe_BYq9YAsc/edit#gid=1906237234

**Comment by herr-zett** [comment]
Apparently this issue references a Use Case rather than actual software. At least the provided link to the [Collaboratory](https://collab.humanbrainproject.eu/#/collab/1655/nav/66850) is listed under the category "Online Use Cases".
With issue #262 we already have a KG-instance describing the Synaptic Events Fitting Notebook.
Furthermore we've closed issue #267 that seems to describe a similar Use Case.

Given this information, should this issue be closed, too?

**Comment by jagru20** [comment]
Yes, this issue is closed as we are not curating models.
