### ISSUE TITLE
HippoUnit 1.3.5

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#307]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1470016597

**Comment by jagru20** [comment]
Dear @appukutan-shailesh, I assume you are used to our revision process already. Could you revise this issue? Thank you very much!

**Comment by appukuttan-shailesh** [comment]
I am a bit confused about which spreadsheet is to be updated..... 
For https://github.com/bweyers/HBPVisCatalogue/issues/302, the spreadsheet updated was:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=1816028149

For the current ticket, the spreadsheet specified is:
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=186124269
This one doesn't have the corrections made for https://github.com/bweyers/HBPVisCatalogue/issues/302.

Isn't all the info being collated in the same spreadsheet?

**Comment by jagru20** [comment]
Sorry for the confusion! I think the comment on this issue has mixed up with E-Mails that I sent to you. In general, the information for each issue (i.e. piece of software) is collected in a spreadsheet for that specific software. The issue you mentioned is only for the Software "BasalUnit" which is already integrated in the Knowledge Graph.

This issue we are currently commenting on is about a different software: "HippoUnit 1.3.5" the link to the spreadsheet is 

> https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=1470016597

The purpose of the comment I made on this issue is to ask you for revision of HippoUnit.
Does this clarify the confusion?

**Comment by appukuttan-shailesh** [comment]
Sure, ok I get it now. I was just probably surprised to see "tabs" in each of the spreadsheets for other software items (and not just a single tab for the specific software issue). But I understand what I need to do, and can ignore the other tabs in a spreadsheet.

I think the confusion arises mainly for devs handling multiple software items, as (if like me) they might be expecting all the info to be filled into the same spreadsheet. Your response now clarifies this. Thanks.

**Comment by appukuttan-shailesh** [comment]
Looks fine; updated a couple of entries.
Let me know if there was anything else to be added.

**Comment by appukuttan-shailesh** [comment]
p.s. just a suggestion.... it would be useful if you can add the respective devs on their tickets under "Assignees".
If this isn't possible, then maybe specify in the ticket body the dev's names?
.... makes its easier to search all the tickets that a dev needs to respond to.

**Comment by jagru20** [comment]
released: https://kg.ebrains.eu/search/instances/Software/3ab6bb29-5a48-43ac-bf53-b307c66505cb
