### ISSUE TITLE
CerebUnit 1.0.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#308]
[](https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=653771896)

EDITED:
https://docs.google.com/spreadsheets/d/16UT4P77wHKbVjqaRaAZTx73VxuxXAzlRHCGvbPtLD-g/edit#gid=884196994

**Comment by herr-zett** [comment]
Within the README.md in the GitHub-repository it is stated, that the repository is at developmental stage. Furthermore there is no documentation of this software, which is why I couldn't fill in all necessary information.

Apparently, this software is made up of three components (CerebTests, CerebModels, CerebData). Should I investigate them further?

**Comment by jagru20** [comment]
@herr-zett yes, please.

**Comment by herr-zett** [comment]
Added new issues for the components of this software:
* CerebTests #409 
* CerebModels #410 
* CerebData #412

**Comment by bweyers** [comment]
@jagru20 will contact developer for getting further information.

**Comment by jagru20** [comment]
Apparently, the author (github user @lungsi most likely) has been asked for further information on 9th of July via Email. No response received yet.

**Comment by jagru20** [comment]
Still no response from @lungsi

**Comment by jagru20** [comment]
This issue is closed for two reasons:
1. There is too little information publicly available to meet our quality standards in metadata curation. 
1. The person we have the contact information of does not react to our requests for more information.
