### ISSUE TITLE
MIP Data Factory 5

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#354]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=538884140

**Comment by AnnHa2019** [comment]
Is this even an application and relevant for us?

**Comment by bweyers** [comment]
Please keep in as we have appropriate contact information. We may send an email to the authors of the tool an ask. Please mark with attention needed.

**Comment by bweyers** [comment]
@jagru20 please contact developer.

**Comment by jagru20** [comment]
Email sent to developer (@ludovicc), but was rejected because I'm not on the whitelist. Hence this way:

Dear Ludovic,
 
we are currently in the process to add metadata on software to the HBP Knowledge Graph. The major purpose is threefold: First, we would like to enable users to search for software additionally to data etc. through the knowledge graph search interface. Second, this enables to further map software to the curated data sets in the knowledge graph, and third, we plan to use this data as basis for provenance data entering the knowledge graph.

This time, we are wondering if you desire your Software “**MIP Data Factory 5**”  to be integrated into the knowledge graph. If yes, please be so kind to fill in the required information into the below linked spreadsheet.

https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=538884140 
 
If you hover the various meta data categories, you get more information on what is actually meant with the various fields of the schema. Please note that these attributes, especially the feature-list, are not final. So if you have any suggestions or comments please let us know.  Therefore, if you have any questions or comments, do not hesitate to contact me or Jun.-Prof. Benjamin Weyers (weyers@uni-trier.de).
 
Please send us short answer to this mail in the moment you finished your revision. Please try to send us feedback in two weeks from now. If you need more time, please let us know!
 
Thanks and kind regards,

Jan

**Comment by jagru20** [comment]
@ludovicc, could you please comment on this?

**Comment by jagru20** [comment]
contacted Mirco Nasuti and Ferath Kherif

**Comment by jagru20** [comment]
insufficient information / not a software
