### ISSUE TITLE
Data Catalogue 1.6.0

### ISSUE THREAD

**Issue by FeldNico** [bweyers/HBPVisCatalogue#359]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=225146295

**Comment by jagru20** [comment]
@ludovicc 

Dear Ludovic Claude,
 
we are currently in the process to add metadata on software to the HBP Knowledge Graph. The major purpose is threefold: First, we would like to enable users to search for software additionally to data etc. through the knowledge graph search interface. Second, this enables to further map software to the curated data sets in the knowledge graph, and third, we plan to use this data as basis for provenance data entering the knowledge graph.
 
In this meta data curation process, we first research meta data of various types of software before we contact the responsible developer or contact person of that software in a second step.
 
Due to the latter, we contact you with the kind request to check the meta data we collected for your software **Data Catalogue 1.6.0** before we make it available in the HBP Knowledge Graph. Please use the following link to add suggestions to the meta data provided in the spreadsheet. If you have specific comments, please use the “Developer Comments” column (column D). In the same column, you may also find questions we had and we would like you to answer by commenting on it or adding additional information to the schema. We would also like to ask you to ignore all other software tools, which are not specifically mentioned above.

https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=225146295
 
If you hover the various meta data categories, you get more information on what is actually meant with the various fields of the schema. Please note that these attributes, especially the feature-list, are not final. So if you have any suggestions or comments please let us know.  Therefore, if you have any questions or comments, do not hesitate to contact me or Jun.-Prof. Benjamin Weyers (weyers@uni-trier.de).
 
Please send us short answer to this mail in the moment you finished your revision. Please try to send us feedback in two weeks from now. If you need more time, please let us know!
 
Thanks and kind regards,

Jan Gründling
Human-Computer Interaction
Department IV, Computer Science
Phone: +49 651 201-2851
Mail: gruendling@uni-trier.de 
Twitter: @HciTrier
Web: https://hci.uni-trier.de
Besucheradresse: H438, Behringstraße 21, 54296 Trier 
 
 University of Trier | Universitätsring 15 | 54296 Trier | Germany
www.uni-trier.de

**Comment by ludovicc** [comment]
Hello, I'm not working anymore for HBP, please contact @nicedexter for this request. But yes, the metadata looks good. Regrds, Ludovic

**Comment by jagru20** [comment]
released
