### ISSUE TITLE
Unicore 8

### ISSUE THREAD

**Issue by PatriziaDuhr** [bweyers/HBPVisCatalogue#400]
https://docs.google.com/spreadsheets/d/1_uZ1EWiWmoojW81UmT_PlGcBtnUSpM6dp0Tr-k4FkEY/edit#gid=529076978

**Comment by PatriziaDuhr** [comment]
@bweyers added google sheet

**Comment by bweyers** [comment]
Send request to fill out the spreadsheet to the developer of the software.

**Comment by BerndSchuller** [comment]
done! let me know if you have further questions!

**Comment by jagru20** [comment]
released

**Comment by jagru20** [comment]
Dear @BerndSchuller,

 I have a question regarding the license of Unicore. You state that it is under BSD-License but as far as I know, that is not a spceific license but the term "BSD-License" refers to the set of all BSD-Licenses. Neither on Sourceforge nor your webpage I was able to find out which one exactly you mean. Different repos in the Unicore GitHub Account refer to BSD-2, but not all of them do, the licenses are quite inconsistent there. Can you state, which license exactly Unicore is published with? Maybe you mean the BSD-4 Clause license, which is the original BSD-License? 

Thank you in advance
Jan

**Comment by BerndSchuller** [comment]
Hi Jan,

We prefer the 2-clause BSD, as in https://github.com/UNICORE-EU/server-bundle/blob/master/LICENSE

Thanks for the note about the inconsistencies in the files in the repos, I'll check and get these sorted. Since historically different people have added license files at different points in time, different formulations do exist. The "spirit" should be the same everywhere though.

Best regards
Bernd

**Comment by jagru20** [comment]
Hi Bernd,
Thank you for the quick answer and the clarification! I figured there was such a reason for the inconsistencies, I totally understand that.

Best
Jan
