### ISSUE TITLE
fastpli v1.1.0a6 

### ISSUE THREAD

**Issue by PatriziaDuhr** [bweyers/HBPVisCatalogue#459]
update to [fastpli 0.9.8](https://github.com/bweyers/HBPVisCatalogue/issues/370)

[Spreadsheet](https://docs.google.com/spreadsheets/d/1i3RtJ0tIUV3zK5JUC5SoEH1s_i7kbIn1gp_PzJcuwCA/edit?usp=sharing)

**Comment by jagru20** [comment]
@fmatuschke, feel free to trigger the [metadata update](https://github.com/bweyers/HBPVisCatalogue/wiki/How-to-start-software-meta-data-curation%3F#update-curated-software) when you want a new version of fastpli integrated into the knowledge graph.


closing this issue because there are frequent changes made to version 1.1.0
